# Generated by Django 4.2.1 on 2024-04-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_post_date_post_date_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_change',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_publication',
        ),
    ]
