# Generated by Django 4.2.1 on 2024-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_post_date_change_remove_post_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
