# Generated by Django 4.2.1 on 2024-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_post_date_change_post_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_change',
            field=models.DateTimeField(default=None),
        ),
    ]
