# Generated by Django 4.2.1 on 2024-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_post_date_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
