# Generated by Django 4.2.1 on 2024-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_post_date_change_alter_post_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
