# Generated by Django 4.2.1 on 2024-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_personalinformation_alter_post_date_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='age',
        ),
    ]
