# Generated by Django 4.2.1 on 2024-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_personalinformation_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
