# Generated by Django 4.2.1 on 2024-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_personalinformation_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='status',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
