# Generated by Django 4.2.1 on 2024-04-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='birthday',
        ),
    ]
