# Generated by Django 4.2.1 on 2024-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_personalinformation_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
