# Generated by Django 4.2.1 on 2024-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_personalinformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
