# Generated by Django 4.2.1 on 2024-04-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
